name: Deploy Employee App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: employee-app
  ECS_CLUSTER: employee-cluster
  ECS_SERVICE: employee-service

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t employee-app .
        docker tag employee-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/employee-app:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/employee-app:latest

    - name: Deploy ECS
      run: |
        aws ecs update-service \
        --cluster employee-cluster \
        --service employee-service \
        --force-new-deployment \
        --region eu-north-1